<?php

$fincaraizEnvironment = env('FINCARAIZ_ENV', 'qa');
$fincaraizUrls = [
    'mock' => 'https://virtserver.swaggerhub.com/Fincaraiz.com.co/Integradores/1.0.0',
    'qa' => 'https://kong-qa.frcol.io/management/api/1.0',
    'production' => 'https://msi-infofinca.fincaraiz.com.co/management/api/1.0',
];

return [

    'mercadolibre' => [
        'client_id' => env('MERCADOLIBRE_CLIENT_ID'),
        'client_secret' => env('MERCADOLIBRE_CLIENT_SECRET'),
        'redirect_uri' => env('MERCADOLIBRE_REDIRECT_URI'),
        'api_url' => env('MERCADOLIBRE_API_URL', 'https://api.mercadolibre.com'),
        'auth_url' => env('MERCADOLIBRE_AUTH_URL', 'https://auth.mercadolibre.com.co'),
        'site_id' => env('MERCADOLIBRE_SITE_ID', 'MCO'),
        'country_id' => env('MERCADOLIBRE_COUNTRY_ID', 'CO'),
        'currency_id' => env('MERCADOLIBRE_CURRENCY_ID', 'COP'),
        'account_key' => env('MERCADOLIBRE_ACCOUNT_KEY', 'shared'),
        'environment' => env('MERCADOLIBRE_ENV', 'production'),
        'webhook_queue' => env('MERCADOLIBRE_WEBHOOK_QUEUE', 'mercadolibre'),
        'default_listing_type' => env('MERCADOLIBRE_DEFAULT_LISTING_TYPE', 'silver'),
    ],

    'fincaraiz' => [
        'environment' => $fincaraizEnvironment,
        'api_url' => env('FINCARAIZ_API_URL', $fincaraizUrls[$fincaraizEnvironment] ?? $fincaraizUrls['qa']),
        'api_key' => env('FINCARAIZ_API_KEY'),
        'client_id' => env('FINCARAIZ_CLIENT_ID'),
        'client_agent' => env('FINCARAIZ_CLIENT_AGENT'),
        'contact_email' => env('FINCARAIZ_CONTACT_EMAIL'),
        'contact_phone' => env('FINCARAIZ_CONTACT_PHONE'),
        'contact_whatsapp' => env('FINCARAIZ_CONTACT_WHATSAPP'),
        'show_exact_address' => env('FINCARAIZ_SHOW_EXACT_ADDRESS', false),
        'dual_offer' => env('FINCARAIZ_DUAL_OFFER', 'rent'),
        'cache_buster_name' => env('FINCARAIZ_CACHE_BUSTER_NAME', 'sucasa-cache'),
        'webhook_id' => env('FINCARAIZ_WEBHOOK_ID'),
        'webhook_verify_token' => env('FINCARAIZ_WEBHOOK_VERIFY_TOKEN'),
        'webhook_url' => env('FINCARAIZ_WEBHOOK_URL'),
        'timeout' => env('FINCARAIZ_TIMEOUT', 30),
        'auto_sync' => env('FINCARAIZ_AUTO_SYNC', false),
        'auto_sync_limit' => env('FINCARAIZ_AUTO_SYNC_LIMIT', 20),
        'auto_sync_scan' => env('FINCARAIZ_AUTO_SYNC_SCAN', 500),
        'reconcile_concurrency' => env('FINCARAIZ_RECONCILE_CONCURRENCY', 4),
        'reconcile_preview_minutes' => env('FINCARAIZ_RECONCILE_PREVIEW_MINUTES', 10),
    ],

    'ciencuadras' => [
        'environment' => env('CIENCUADRAS_ENV', 'production'),
        'api_url' => env('CIENCUADRAS_API_URL', 'https://ws-api.ciencuadras.com'),
        'page_url' => env('CIENCUADRAS_PAGE_URL', 'https://www.ciencuadras.com'),
        'username' => env('CIENCUADRAS_USERNAME', env('CIENCUADRAS_EMAIL')),
        'email' => env('CIENCUADRAS_EMAIL'),
        'password' => env('CIENCUADRAS_PASSWORD'),
        'integrator' => env('CIENCUADRAS_INTEGRATOR', 'SUCASA'),
        'property_code_prefix' => env('CIENCUADRAS_PROPERTY_CODE_PREFIX', '22130-'),
        'default_city_id' => env('CIENCUADRAS_DEFAULT_CITY_ID'),
        'default_locality_id' => env('CIENCUADRAS_DEFAULT_LOCALITY_ID'),
        'show_address' => env('CIENCUADRAS_SHOW_ADDRESS', false),
        'approximate_location_precision' => env('CIENCUADRAS_APPROXIMATE_LOCATION_PRECISION', 2),
        'default_latitude' => env('CIENCUADRAS_DEFAULT_LATITUDE'),
        'default_longitude' => env('CIENCUADRAS_DEFAULT_LONGITUDE'),
        'contact_name' => env('CIENCUADRAS_CONTACT_NAME', 'Su Casa Inmobiliaria'),
        'contact_phone' => env('CIENCUADRAS_CONTACT_PHONE'),
        'contact_email' => env('CIENCUADRAS_CONTACT_EMAIL'),
        'contact_whatsapp' => env('CIENCUADRAS_CONTACT_WHATSAPP'),
        'auto_sync' => env('CIENCUADRAS_AUTO_SYNC', false),
        'auto_sync_limit' => env('CIENCUADRAS_AUTO_SYNC_LIMIT', 20),
        'auto_sync_scan' => env('CIENCUADRAS_AUTO_SYNC_SCAN', 500),
        'verify_max_attempts' => env('CIENCUADRAS_VERIFY_MAX_ATTEMPTS', 30),
    ],

    'proppit' => [
        'api_url' => env('PROPPIT_API_URL', 'https://real-time.proppit.com/api/v2'),
        'country' => env('PROPPIT_COUNTRY', 'CO'),
        // Proppit entrega estas credenciales como Client ID / Client Secret,
        // aunque su endpoint /token exige enviarlas como user / password.
        'user' => env('PROPPIT_CLIENT_ID', env('PROPPIT_USER')),
        'password' => env('PROPPIT_CLIENT_SECRET', env('PROPPIT_PASSWORD')),
        'publisher_external_id' => env('PROPPIT_PUBLISHER_EXTERNAL_ID'),
        'default_contact_name' => env('PROPPIT_DEFAULT_CONTACT_NAME', 'Su Casa Inmobiliaria'),
        'default_contact_email' => env('PROPPIT_DEFAULT_CONTACT_EMAIL'),
        'default_contact_phone' => env('PROPPIT_DEFAULT_CONTACT_PHONE'),
        'location_visibility' => env('PROPPIT_LOCATION_VISIBILITY', 'approximate'),
        'boosted_weekly_limit' => env('PROPPIT_BOOSTED_WEEKLY_LIMIT', 1),
        'boost_new_listings' => env('PROPPIT_BOOST_NEW_LISTINGS', true),
        'boosted_refresh_limit' => env('PROPPIT_BOOSTED_REFRESH_LIMIT', 300),
        'auto_sync' => env('PROPPIT_AUTO_SYNC', false),
        'auto_sync_limit' => env('PROPPIT_AUTO_SYNC_LIMIT', 20),
        'auto_sync_scan' => env('PROPPIT_AUTO_SYNC_SCAN', 500),
        'public_url' => env('PROPPIT_PUBLIC_URL'),
    ],

];
